# Generated by Django 2.2.12 on 2020-08-12 14:34

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mobile_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('-date_joined',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_flat', models.CharField(blank=True, max_length=32, null=True)),
                ('road_no', models.CharField(blank=True, max_length=32, null=True)),
                ('address_line1', models.CharField(max_length=120)),
                ('address_line2', models.CharField(blank=True, max_length=120, null=True)),
                ('mobile_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('country', django_countries.fields.CountryField(help_text='Billing Country', max_length=2)),
                ('postal_code', models.CharField(help_text='Postal Code', max_length=20)),
                ('city', models.ForeignKey(help_text='Billing City', on_delete=django.db.models.deletion.CASCADE, related_name='shipping_city', to='shop.City')),
                ('state', models.ForeignKey(help_text='Billing State', on_delete=django.db.models.deletion.CASCADE, related_name='shipping_state', to='shop.State')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_flat', models.CharField(blank=True, max_length=32, null=True)),
                ('road_no', models.CharField(blank=True, max_length=32, null=True)),
                ('address_line1', models.CharField(max_length=120)),
                ('address_line2', models.CharField(blank=True, max_length=120, null=True)),
                ('mobile_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('country', django_countries.fields.CountryField(help_text='Billing Country', max_length=2)),
                ('postal_code', models.CharField(help_text='Postal Code', max_length=20)),
                ('city', models.ForeignKey(help_text='Billing City', on_delete=django.db.models.deletion.CASCADE, related_name='billing_city', to='shop.City')),
                ('state', models.ForeignKey(help_text='Billing State', on_delete=django.db.models.deletion.CASCADE, related_name='billing_state', to='shop.State')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_address_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
