# Generated by Django 2.2.12 on 2020-09-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbillingaddress',
            name='mobile_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=17),
        ),
    ]
