# Generated by Django 2.2.12 on 2020-08-12 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='variant_options',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='label',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='value',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.DeleteModel(
            name='ProductVariantOption',
        ),
        migrations.DeleteModel(
            name='ProductVariantValue',
        ),
    ]
