# Generated by Django 2.2.12 on 2020-08-12 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200812_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='label',
            new_name='option',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
