# Generated by Django 2.2.12 on 2020-08-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(default=None, null=True, unique='products/variants/', upload_to=''),
        ),
    ]
