# Generated by Django 2.2.12 on 2020-08-12 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_productimage_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_images',
        ),
    ]
