# Generated by Django 2.2.12 on 2020-08-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200812_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='products/variants/'),
        ),
    ]
