# Generated by Django 2.2.12 on 2020-08-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
