# Generated by Django 2.2.12 on 2020-08-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_productcategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageBannerSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, upload_to='homepage/slider/')),
                ('heading', models.CharField(max_length=120, null=True)),
                ('sub_heading', models.CharField(max_length=250, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('-created',),
            },
        ),
    ]
