# Generated by Django 2.2.12 on 2020-08-17 11:11

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20200817_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagebannerslider',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default=None, upload_to='homepage/slider/'),
        ),
    ]
